<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swift</string>
		<string>swiftinterface</string>
	</array>
	<key>name</key>
	<string>Swift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.swift</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.swift</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.swift</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.swift</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>comment.punctuation.comma.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|deinit|enum|extension|func|import|init|let|protocol|static|struct|subscript|typealias|var|break|case|continue|default|do|else|fallthrough|if|in|for|return|switch|where|while|as|dynamicType|is|new|super|self|Self|Type|__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|didSet|get|infix|inout|left|mutating|none|nonmutating|operator|override|postfix|precedence|prefix|right|set|unowned|weak|willSet)\b</string>
			<key>name</key>
			<string>keyword.reserved.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>meta.tag.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*\()</string>
			<key>name</key>
			<string>support.function.swift</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.swift</string>
	<key>uuid</key>
	<string>6A273AF0-EB4A-11E3-AC10-0800200C9A66</string>
</dict>
</plist>